name: Deploy Quarto Documentation

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Dependencies
        run: |
          # Only run pip install if requirements.txt is present
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No Python dependencies to install."
          fi

      - name: Render Quarto Site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.QUARTO_TOKEN}}
          publish_dir: ./public
